#####################################################################################
########                          Configuration file                         ########
#####################################################################################

version: 0.1